### ISSUE TITLE
Group Name

### ISSUE THREAD

**Issue by sara-shahin-cell** [MIT-Emerging-Talent/ET6-foundations-group-21#3]
What do you suggest to name our group?

We are looking for a creative and meaningful name for our group. The name should reflect our purpose and values.

**Comment by Solarahamza** [comment]
Hello Nour,
So I asked ChatGPT for help and these are some of the names that I liked are
"Data newbies, "NextGen Data Minds" and "Rising Data Stars"

**Comment by Fikre-Mamo** [comment]
Sounds great to me "Rising Data Stars"

**Comment by sara-shahin-cell** [comment]
Thanks, @Solarahamza for suggestions.
I'll go for  "Rising Data Stars" as well.

**Comment by collyns-linc** [comment]
The suggestions by @Solarahamza , for the `Rising Data Stars` is great👌.

**Comment by Tahershaba** [comment]
Hello everyone I am ok with "Rising Data Stars"

**Comment by omerdafaalla** [comment]
Thanks to @Solarahamza for the great suggestions, I agree with " Rising Data Stars"
