### ISSUE TITLE
Setting Learning Goals

### ISSUE THREAD

**Issue by collyns-linc** [MIT-Emerging-Talent/ET6-foundations-group-21#7]
# Learning Goals

## Collective        
These focus on the goals that benefit a group or team working together toward shared objectives( e.g Collaboration skills, Communications, goal alignment..)

-
-

## Individual

These focus on the personal growth and achievements of each member within the group (e.g Skill mastery, time management, adaptability...) 

-
-

**Comment by Fikre-Mamo** [comment]
# Learning Goals
 
 ## 1. Group Objectives
 - **Project Success**: Complete your first project as a cohesive team while meeting quality standards.  
 - **Learning Through Collaboration**: Enhance programming skills through teamwork, sharing knowledge, and solving 
 
 ---
 
 ## 2. Collective Goals
 - **Establish Team Norms**: Define clear guidelines for communication, task distribution, and code quality standards.
 - **Master Debugging**: Work together on identifying and resolving bugs to improve problem-solving efficiency.   
 - **add your Collective Goals Here**   
 
 ---
 
 ## 3. Individual Goals
 - **Fikre's Goals**: 
   - Focus on learning structured problem-solving techniques.  
   - Contribute actively to discussions during code reviews.  
 
 - **Team Member A's Goal**:  
   - add your Goals Here  
   
 - **Team Member B's Goal**:  
   - add your Goals Here 
 
 - **Team Member C's Goal**:  
   - add your Goals Here  
 
 ---
 
 ## 4. Summary
 - **Shared Vision**:
 - **Collaboration Focus**:   
 - **Feedback Loops**:   
 - **Iterative Improvement**:

**Comment by KimaciaJnr** [comment]
### Learning Goals

#### Collective Goals
1. Foster collaboration and teamwork as the foundation of the group project. Encourage an environment where everyone feels free to express their opinions and all members are willing to assist or provide constructive feedback respectfully.  
2. Ensure efficiency in all aspects of the project, including attending meetings, completing assigned tasks, and delivering the project on time while adhering to best coding practices.

#### Individual Goals
1. Commit to punctuality and active participation in group meetings, ensure timely completion of assigned tasks, and maintain a readiness to seek or offer assistance to team members when needed.  
2. Develop proficiency in debugging and gain a deeper understanding of code implementation and strategy.

**Comment by Solarahamza** [comment]
Individual Goals
Build confidence in using GitHub, VS Code, and Python effectively.
Foster strong relationships with group members and actively learn from their expertise
Develop proficiency as a code reviewer and debugger.

**Comment by omerdafaalla** [comment]
Collective Goals:
 1. Emphasize shared accountability and responsibility to keep the project on track and aligned with objectives.
 2. Maintain clear and respectful communication to keep the team aligned on objectives and progress.

  Individual Goals:

 1. Master Python basics and explore advanced concepts to write better code.
 2. Develop debugging skills by systematically analyzing and resolving code issues using tools and resources effectively.
 4. Understand and use GitHub in projects with multiple programmers contributing.

**Comment by sara-shahin-cell** [comment]
**Collective Goals:**
1. Foster effective teamwork through active participation and mutual support.
2. Strengthen team communication by ensuring clarity, active listening, and regular updates.

**Individual Goals:**
1. Focus on developing expertise in Git and GitHub to enhance personal performance.
Time Management:
2. Improve the ability to prioritize tasks and manage time efficiently for better productivity.

**Comment by Tahershaba** [comment]
Collective Goals
1-Foster effective collaboration by practicing code reviews, pair programming, and collaborative problem-solving using GitHub.
2-Strengthen communication skills within the team by utilizing GitHub issues, pull requests, and project boards for transparent project tracking and feedback.
3-Develop a shared understanding of project timelines, deadlines, and deliverables, tracking milestones using GitHub Projects or other tools.

Individual Goals
1-Gain proficiency in Git and GitHub functionalities, including advanced features like rebasing, tagging, and stashing.
2-Develop a disciplined workflow by adhering to deadlines for individual contributions.
3-Respond constructively to feedback and use it to improve personal contributions.
